const $ = (s, root=document) => root.querySelector(s);
const $$ = (s, root=document) => [...root.querySelectorAll(s)];
const starterItems = [
{id:'rw1',name:'Sage linen shirt',category:'Tops',size:'M',condition:'Like new',value:850,location:'Noida',owner:'Maya',description:'Lightweight linen blend, relaxed fit and an easy everyday layer.',image:'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=700&q=80'},
{id:'rw2',name:'Everyday denim',category:'Bottoms',size:'S',condition:'Gently used',value:1100,location:'Delhi',owner:'Aarav',description:'Classic blue denim with a straight-leg fit. No major signs of wear.',image:'https://images.unsplash.com/photo-1542272604-787c3835535d?auto=format&fit=crop&w=700&q=80'},
{id:'rw3',name:'Floral midi dress',category:'Dresses',size:'M',condition:'Like new',value:1400,location:'Ghaziabad',owner:'Isha',description:'Soft floral print, flowy silhouette and perfect for a sunny day.',image:'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&w=700&q=80'},
{id:'rw4',name:'Weekend knit',category:'Tops',size:'L',condition:'Gently used',value:700,location:'Noida',owner:'Rohan',description:'Comfortable textured knit in a neutral shade. Freshly washed.',image:'https://images.unsplash.com/photo-1618354691373-d851c5c3a990?auto=format&fit=crop&w=700&q=80'},
{id:'rw5',name:'Classic trench coat',category:'Outerwear',size:'M',condition:'Like new',value:2200,location:'Delhi',owner:'Meera',description:'Timeless layering piece in a versatile beige colour.',image:'https://images.unsplash.com/photo-1548624149-f1f1b4e5a7b6?auto=format&fit=crop&w=700&q=80'},
{id:'rw6',name:'Canvas sneakers',category:'Shoes',size:'L',condition:'Gently used',value:950,location:'Faridabad',owner:'Kabir',description:'Minimal everyday sneakers, clean soles and plenty of life left.',image:'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=700&q=80'},
{id:'rw7',name:'Soft cotton tee',category:'Tops',size:'XL',condition:'Well loved',value:350,location:'Noida',owner:'Tara',description:'A soft cotton basic with a relaxed fit and a lot of wear left.',image:'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&w=700&q=80'},
{id:'rw8',name:'Woven shoulder bag',category:'Accessories',size:'Free size',condition:'Like new',value:1200,location:'Gurugram',owner:'Naina',description:'Neutral woven bag with room for everyday essentials.',image:'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=700&q=80'}
];
const getStore=(key,fallback)=>{try{const v=localStorage.getItem(key);return v?JSON.parse(v):fallback}catch{return fallback}};
let items=getStore('rewear_items',starterItems), requests=getStore('rewear_requests',[]), favorites=new Set(getStore('rewear_favorites',[])), profile=getStore('rewear_profile','');
const save=()=>{localStorage.setItem('rewear_items',JSON.stringify(items));localStorage.setItem('rewear_requests',JSON.stringify(requests));localStorage.setItem('rewear_favorites',JSON.stringify([...favorites]));localStorage.setItem('rewear_profile',JSON.stringify(profile));};
const esc=(s='')=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const safeImage=(url)=>/^https:\/\//i.test(url||'')?url:'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=700&q=80';
let toastTimer;
function toast(msg){const el=$('#toast');el.textContent=msg;el.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.remove('show'),2800)}
function renderItems(){const q=$('#searchInput').value.trim().toLowerCase(),cat=$('#categoryFilter').value,size=$('#sizeFilter').value,cond=$('#conditionFilter').value,loc=$('#locationFilter').value.trim().toLowerCase();const filtered=items.filter(i=>(!q||[i.name,i.category,i.description,i.owner,i.location].join(' ').toLowerCase().includes(q))&&(cat==='all'||i.category===cat)&&(size==='all'||i.size===size)&&(cond==='all'||i.condition===cond)&&(!loc||i.location.toLowerCase().includes(loc)));$('#productGrid').innerHTML=filtered.map(i=>`<article class="product-card"><div class="product-image"><img src="${esc(safeImage(i.image))}" alt="${esc(i.name)}" loading="lazy" onerror="this.src='https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=700&q=80'"><span class="condition-pill">${esc(i.condition)}</span><button class="heart-btn ${favorites.has(i.id)?'active':''}" data-favorite="${esc(i.id)}" aria-label="Save ${esc(i.name)}">${favorites.has(i.id)?'♥':'♡'}</button></div><div class="product-info"><div class="product-meta"><span>${esc(i.category)} · Size ${esc(i.size)}</span><span>⌖ ${esc(i.location)}</span></div><h3 class="product-title">${esc(i.name)}</h3><p class="product-desc">${esc(i.description||'A pre-loved piece ready for a new home.')}</p><div class="product-bottom"><div class="value-label">₹${Number(i.value).toLocaleString('en-IN')}<small>Estimated swap value</small></div><button class="btn btn-dark swap-btn" data-swap="${esc(i.id)}">Request swap ↗</button></div></div></article>`).join('');$('#emptyState').classList.toggle('hidden',filtered.length!==0);$('#productGrid').classList.toggle('hidden',filtered.length===0);$('#resultsCount').textContent=`Showing ${filtered.length} ${filtered.length===1?'piece':'pieces'}`;$('#statItems').textContent=String(items.length).padStart(2,'0');$('#requestBadge').textContent=requests.filter(r=>r.status==='Pending').length;}
function openModal(id){$('#'+id).classList.remove('hidden');document.body.style.overflow='hidden'}function closeModal(id){$('#'+id).classList.add('hidden');if(!$$('.modal-backdrop:not(.hidden)').length)document.body.style.overflow=''}
function openSwap(id){const item=items.find(i=>i.id===id);if(!item)return;$('#swapItemInfo').innerHTML=`<img src="${esc(safeImage(item.image))}" alt=""><div><b>${esc(item.name)}</b><small>Size ${esc(item.size)} · ${esc(item.location)} · Est. ₹${Number(item.value).toLocaleString('en-IN')}</small><small>Listed by ${esc(item.owner)}</small></div>`;$('#swapForm').elements.itemId.value=id;$('#swapForm').elements.requester.value=profile;openModal('swapModal')}
function renderRequests(){const root=$('#requestsList');if(!requests.length){root.innerHTML='<div class="empty-state"><div>⇄</div><h3>No swap requests yet</h3><p>When you request a swap, it will appear here.</p></div>';return}root.innerHTML=[...requests].reverse().map(r=>`<article class="request-card"><h4>${esc(r.itemName)}</h4><p><b>From:</b> ${esc(r.requester)} · <b>Listed by:</b> ${esc(r.owner)}</p><p><b>Offer / message:</b> ${esc(r.offer)}</p><p><b>Created:</b> ${esc(r.created)}</p><span class="request-status">${esc(r.status)}</span>${r.status==='Pending'?`<div class="request-actions"><button class="btn btn-outline" data-status="Accepted" data-request="${esc(r.id)}">Accept</button><button class="btn btn-outline" data-status="Declined" data-request="${esc(r.id)}">Decline</button></div>`:''}</article>`).join('')}
function renderAdmin(){const pending=requests.filter(r=>r.status==='Pending').length;$('#adminStats').innerHTML=`<div class="admin-stat"><b>${items.length}</b><span>Active listings</span></div><div class="admin-stat"><b>${requests.length}</b><span>Total requests</span></div><div class="admin-stat"><b>${pending}</b><span>Pending requests</span></div>`;$('#adminListings').innerHTML=items.length?items.map(i=>`<div class="admin-row"><img src="${esc(safeImage(i.image))}" alt=""><div class="admin-name"><b>${esc(i.name)}</b><small>${esc(i.owner)} · ₹${Number(i.value).toLocaleString('en-IN')}</small></div><button data-delete="${esc(i.id)}">Remove</button></div>`).join(''):'<p class="muted">No listings yet.</p>'}
function refresh(){save();renderItems();}
['searchInput','categoryFilter','sizeFilter','conditionFilter','locationFilter'].forEach(id=>$('#'+id).addEventListener(id==='searchInput'||id==='locationFilter'?'input':'change',renderItems));$('#resetFilters').addEventListener('click',()=>{$('#searchInput').value='';$('#categoryFilter').value='all';$('#sizeFilter').value='all';$('#conditionFilter').value='all';$('#locationFilter').value='';renderItems()});
['openListing','heroList','marketList','impactList','emptyList'].forEach(id=>$('#'+id).addEventListener('click',()=>{if(profile)$('#listingForm').elements.owner.value=profile;openModal('listingModal')}));$('#loginBtn').addEventListener('click',()=>{if(profile)$('#profileForm').elements.profileName.value=profile;openModal('loginModal')});$('#requestsBtn').addEventListener('click',()=>{renderRequests();openModal('requestsModal')});$('#viewRequests').addEventListener('click',()=>{closeModal('loginModal');renderRequests();openModal('requestsModal')});$('#adminBtn').addEventListener('click',()=>{closeModal('loginModal');renderAdmin();openModal('adminModal')});$('#menuToggle').addEventListener('click',()=> $('nav').classList.toggle('open'));$$('nav a').forEach(a=>a.addEventListener('click',()=> $('nav').classList.remove('open')));
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>closeModal(b.dataset.close)));$$('.modal-backdrop').forEach(b=>b.addEventListener('click',e=>{if(e.target===b)closeModal(b.id)}));document.addEventListener('keydown',e=>{if(e.key==='Escape')$$('.modal-backdrop:not(.hidden)').forEach(m=>closeModal(m.id))});
$('#listingForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),v=Object.fromEntries(f.entries());const item={id:'rw'+Date.now(),name:v.name.trim(),category:v.category,size:v.size,condition:v.condition,value:Number(v.value),location:v.location.trim(),owner:v.owner.trim(),description:v.description.trim()||'A pre-loved piece ready for a new home.',image:v.image.trim()||'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=700&q=80'};items.unshift(item);profile=item.owner;refresh();e.currentTarget.reset();closeModal('listingModal');renderItems();toast('Your item is now listed in this demo!');$('#marketplace').scrollIntoView({behavior:'smooth'})});
$('#swapForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.currentTarget),v=Object.fromEntries(f.entries()),item=items.find(i=>i.id===v.itemId);if(!item)return toast('This item is no longer available.');if(v.requester.trim().toLowerCase()===item.owner.trim().toLowerCase())return toast('Try requesting a swap from another member.');requests.push({id:'req'+Date.now(),itemId:item.id,itemName:item.name,owner:item.owner,requester:v.requester.trim(),offer:v.offer.trim(),created:new Date().toLocaleDateString(),status:'Pending'});profile=v.requester.trim();refresh();e.currentTarget.reset();closeModal('swapModal');toast('Swap request saved! Open the requests panel to view it.');});
$('#profileForm').addEventListener('submit',e=>{e.preventDefault();profile=e.currentTarget.elements.profileName.value.trim();save();closeModal('loginModal');toast(`Display name saved: ${profile}`)});
document.addEventListener('click',e=>{const fav=e.target.closest('[data-favorite]');if(fav){const id=fav.dataset.favorite;favorites.has(id)?favorites.delete(id):favorites.add(id);save();renderItems();return}const swap=e.target.closest('[data-swap]');if(swap){openSwap(swap.dataset.swap);return}const status=e.target.closest('[data-status]');if(status){const r=requests.find(x=>x.id===status.dataset.request);if(r){r.status=status.dataset.status;save();renderRequests();renderItems();toast(`Request ${r.status.toLowerCase()}.`)}return}const del=e.target.closest('[data-delete]');if(del){items=items.filter(i=>i.id!==del.dataset.delete);favorites.delete(del.dataset.delete);refresh();renderAdmin();toast('Listing removed from this browser.')}});
$('#resetDemo').addEventListener('click',()=>{if(!confirm('Reset all local demo listings and requests?'))return;items=[...starterItems];requests=[];favorites=new Set();profile='';refresh();renderAdmin();renderItems();toast('Demo data reset.')});
renderItems();
